name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify Python 3.11 instead of 3.x
          cache: pip

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libcairo2-dev \
            libfreetype6-dev \
            libffi-dev \
            libjpeg-dev \
            libpng-dev \
            libz-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Build site
        run: mkdocs build
        if: github.event_name == 'pull_request'
